### ISSUE TITLE
[Feature] Upload and analyze a package.json file

### ISSUE THREAD

**Issue by petermikitsh** [solids/npmsearch#31]
Use case: I'm new to npmsearch.com. I want to see the scores for all the modules listed in my project's package.json file, sorted by score, that way I can see if I have any questionable package dependencies installed.

I've suggested this feature at dylang/npm-check#111 and and depcheck/depcheck#134. Both projects found the suggestion to be out-of-scope. Maybe it's a feature best suited for the npmsearch.com website.

**Comment by tmpvar** [comment]
hrm, this is interesting.  It's easy enough to get the score from the api

example: https://npmsearch.com/query?q=_id:jsdom+_id:vec2&fields=rating,name

The issue with adding this to npmsearch.com is that it sort of detracts from how simple the page is. The alternative is a ~10 line file (minus dependencies) that can do exactly what you want.

Also for ease of use, I think it makes more sense to be run in a local directory rather than having to search your disk for a directory to upload a file.

I'll think about it, but my general thought on this is no

**Comment by petermikitsh** [comment]
The value add would be that you wouldn't have to write 10 lines of code or be familiar with elastic search's query api. I don't feel it would detract much from the simplicity of the site. I agree, it makes more sense to run it locally, but npm-check and depcheck shot it down.

Maybe it's just a bad idea. I'm OK with that.

**Comment by tmpvar** [comment]
> Maybe it's just a bad idea. I'm OK with that.

I'm not saying that, but if you write the 10 lines and publish as a package then everyone can use the tool.  I dunno.

**Comment by tmpvar** [comment]
@petermikitsh I've gone ahead and written the thing for you: https://github.com/tmpvar/npmsearch-local-ratings

`$ npm install -g npmsearch-local-ratings`

and run it in a directory with a package.json

`$ npmsearch-local-ratings`

**Comment by petermikitsh** [comment]
You're too kind.
